// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storage.Data;

namespace Storage.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20201008140832_add-more-products")]
    partial class addmoreproducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Storage.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "livingroom",
                            Count = 5,
                            Description = "60 inches ",
                            Name = "tv",
                            Orderdate = new DateTime(2008, 3, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 20000,
                            Shelf = "B110"
                        },
                        new
                        {
                            Id = 2,
                            Category = "kitchen",
                            Count = 5,
                            Description = "medums ",
                            Name = "dish",
                            Orderdate = new DateTime(2018, 3, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50,
                            Shelf = "A10"
                        },
                        new
                        {
                            Id = 3,
                            Category = "livingroom",
                            Count = 5,
                            Description = "black ",
                            Name = "radio",
                            Orderdate = new DateTime(2020, 3, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1000,
                            Shelf = "C110"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
